name: Moodle plugin CI for Moodle 3.3

on:
  workflow_call:
    inputs:
      extra_plugin_runners:
        type: string

jobs:
  setup:
    name: CI test for Moodle 3.3
    env:
      IGNORE_PATHS: tests/fixtures
    runs-on: 'ubuntu-latest'

    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        ports:
          - 5432:5432

      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        database: ['mariadb', 'pgsql']
        moodle-branch: ['MOODLE_33_STABLE']
        node: ['14.15']
        php: ['7.1', '7.2']

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: plugin

      - name: Install node  ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pgsql, mysqli, zip, gd, xmlrpc, soap
          coverage: none

      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          # Add dirs to $PATH
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          # PHPUnit depends on en_AU.UTF-8 locale
          sudo locale-gen en_AU.UTF-8

      - name: Install dependencies
        if: ${{ inputs.extra_plugin_runners }}
        run: |
          ${{ inputs.extra_plugin_runners }}

      - name: Install Moodle
        run:  moodle-plugin-ci install -vvv --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: Run phplint
        if: ${{ always() }}
        run: moodle-plugin-ci phplint

      - name: Run codechecker
        if: ${{ always() }}
        run: moodle-plugin-ci codechecker

      - name: Run validate
        if: ${{ always() }}
        run: moodle-plugin-ci validate

      - name: Run savepoints
        if: ${{ always() }}
        run: moodle-plugin-ci savepoints

      - name: Run mustache
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci mustache

      - name: Run grunt
        if: ${{ always() }}
        run: moodle-plugin-ci grunt

      - name: Run phpunit
        if: ${{ always() }}
        run: |
          moodle-plugin-ci phpunit
          cd moodle
          vendor/bin/phpunit --fail-on-risky --disallow-test-output --filter tool_dataprivacy_metadata_registry_testcase
          vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite core_privacy_testsuite --filter provider_testcase

      - name: Run behat
        if: ${{ always() }}
        run: moodle-plugin-ci behat --profile chrome

      - name: PHP Copy/Paste Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpcpd

      - name: PHP Mess Detector
        continue-on-error: true # This step will show errors but will not fail
        if: ${{ always() }}
        run: moodle-plugin-ci phpmd
